name: "Test RPI image as Systemd container"
on:
  push:
    branches:
      - "**"

jobs:
  test-img:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/checkout@v3
        with:
          repository: 'nextcloud/nextcloudpi'
          ref: devel
      - name: Prepare image
        run: |
          set -ex
          sudo apt install systemd-container
          sudo pip install selenium
          wget -q -O ncp.tar.gz https://github.com/nextcloud/nextcloudpi/releases/download/v1.48.3/NextCloudPi_RPi_07-25-22.tar.gz
          tar xf ncp.tar.gz
          mv NextCloudPi_*.img ncp.img
          source ./build/buildlib.sh
          mount_raspbian ncp.img
          wget -q https://github.com/multiarch/qemu-user-static/releases/latest/download/qemu-aarch64-static -O ./qemu-aarch64-static
          sudo cp qemu-aarch64-static raspbian_root/usr/bin/
          echo 'Mutex posixsem' | sudo tee -a raspbian_root/etc/apache2/mods-available/ssl.conf

      - name: Run and test
        run: |
          set -ex
          sudo systemd-nspawn --boot -D ./raspbian_root/ -M ncp --hostname=nextcloudpi &> container.log &
          
          sleep 30
          success=false
          for i in {1..50}
          do
            echo ":: Wait for container to startup (attempt $i/50) ::"
            ip="$(cat container.log | grep 'My IP address is' | cut -d ' ' -f5)"
            curl -k "https://$ip/activate" > /dev/null || { sleep 6; continue; }
            success=true
          done
          
          [[ "$success" == "true" ]] || {
            echo "Could not reach container. Aborting..."
            echo "Container logs:"
            cat container.log
            exit 1
          }
          
          success=false
          for attempt in {1..3}
          do
            echo ":: Activation Tests (attempt $i/3) ::"
            python tests/activation_tests.py --no-gui "$ip" 443 4443 || {
              echo "Activation test failed!"
              echo "Geckodriver logs:"
              tail -n 20 geckodriver.log >&2 || true
              echo "================"
              echo "ncp.log: "
              machinectl shell ncp /bin/bash -c "tail -n20 /var/log/ncp.log"
              sleep 6
              continue
            }
            success=true
            break
          done
          [[ "$success" == "true" ]] || exit 1
          
          success=false
          for attempt in {1..3}
          do
            echo ":: System Tests (attempt $i/3) ::"
            sudo python tests/system_tests.py --non-interactive || {
              echo "System test failed!"
              sleep 6
              continue
            }
            success=true
            break
          done
          [[ "$success" == "true" ]] || exit 1
          
          success=false
          for attempt in {1..3}
          do
            echo ":: Nextcloud Tests (attempt $i/3) ::"
            python tests/nextcloud_tests.py --no-gui "$ip" 443 4443 || {
              echo "Nextcloud test failed!"
              echo "Geckodriver logs:"
              tail -n 20 geckodriver.log >&2 || true
              echo "================"
              echo "ncp.log: "
              machinectl shell ncp /bin/bash -c "tail -n20 /var/log/ncp.log"
              sleep 6
              continue
            }
            success=true
            break
          done
          
          result=$?
          sudo machinectl terminate ncp || true
          exit "$result"